import type { HireProject, BuilderMatch, Invitation } from "@/types";

export const MOCK_HIRE_PROJECTS: HireProject[] = [
  {
    id: "hp-1",
    creator_id: "f1",
    title: "AI Customer Support Chatbot",
    description: "I need an AI chatbot that handles customer support tickets. It should use Claude, integrate with Slack and Intercom, and learn from past conversations to improve over time. Must handle 50+ tickets/day with <5% escalation rate.",
    ai_parsed_requirements: {
      core_requirement: "AI chatbot for customer support with learning capabilities",
      integrations: ["Slack", "Intercom", "Zendesk"],
      tech_stack: ["Claude API", "Python", "FastAPI", "PostgreSQL"],
      complexity: "medium",
      ideal_builder_type: "Full-stack AI engineer with chatbot experience",
    },
    budget_min: 5000,
    budget_max: 12000,
    budget_currency: "USD",
    timeline_weeks: 4,
    category: "AI Agents",
    scope: "medium",
    complexity: "medium",
    required_skills: ["Claude", "Python", "API Integration", "AI Agents"],
    preferred_tech_stack: ["Claude API", "FastAPI", "PostgreSQL", "Slack API"],
    success_criteria: "Handle 50+ tickets/day, <5% escalation, Slack + Intercom integration working, continuous learning from past tickets",
    status: "open",
    visibility: "public",
    views_count: 47,
    interest_count: 3,
    created_at: "2026-07-18T10:00:00Z",
    updated_at: "2026-07-21T14:00:00Z",
    creator: {
      id: "f1",
      username: "sarahchen",
      full_name: "Sarah Chen",
      avatar_url: null,
      bio: "Founder & CEO at SupportAI",
      stack: ["Product", "Design", "AI"],
      social_links: {},
      github_username: "sarahchen",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 88,
      role: "founder",
      is_verified: true,
      created_at: "2026-01-01T00:00:00Z",
      updated_at: "2026-07-01T00:00:00Z",
    },
  },
  {
    id: "hp-2",
    creator_id: "f2",
    title: "Real-Time Data Pipeline with Kafka",
    description: "Build a real-time data ingestion pipeline using Kafka, Python, and Postgres. Needs to handle 10k events/sec, with monitoring dashboard and alerting.",
    ai_parsed_requirements: {
      core_requirement: "Real-time data ingestion pipeline with Kafka",
      integrations: ["Kafka", "Grafana", "PagerDuty"],
      tech_stack: ["Kafka", "Python", "PostgreSQL", "Docker"],
      complexity: "high",
      ideal_builder_type: "Data engineer with Kafka expertise",
    },
    budget_min: 10000,
    budget_max: 25000,
    budget_currency: "USD",
    timeline_weeks: 8,
    category: "Data Engineering",
    scope: "large",
    complexity: "high",
    required_skills: ["Kafka", "Python", "PostgreSQL", "Docker", "Grafana"],
    preferred_tech_stack: ["Apache Kafka", "Python 3.12", "PostgreSQL 16", "Docker Compose"],
    success_criteria: "10k events/sec throughput, <100ms latency, Grafana dashboard with alerts, 99.9% uptime",
    status: "open",
    visibility: "public",
    views_count: 32,
    interest_count: 5,
    created_at: "2026-07-16T08:00:00Z",
    updated_at: "2026-07-20T16:00:00Z",
    creator: {
      id: "f2",
      username: "marcusj",
      full_name: "Marcus Johnson",
      avatar_url: null,
      bio: "CTO at DataFlow Inc",
      stack: ["Data Engineering", "Infrastructure", "Python"],
      social_links: {},
      github_username: "marcusj",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 92,
      role: "founder",
      is_verified: true,
      created_at: "2026-01-15T00:00:00Z",
      updated_at: "2026-07-05T00:00:00Z",
    },
  },
  {
    id: "hp-3",
    creator_id: "f3",
    title: "RAG Knowledge Base System",
    description: "Build a RAG (Retrieval Augmented Generation) system that indexes our internal documentation and lets users ask questions in natural language. Needs Qdrant for vector storage, GPT-4o for generation, and a React frontend.",
    ai_parsed_requirements: {
      core_requirement: "RAG system for internal documentation Q&A",
      integrations: ["Qdrant", "OpenAI", "Slack"],
      tech_stack: ["Python", "LangChain", "Qdrant", "React", "GPT-4o"],
      complexity: "medium",
      ideal_builder_type: "ML engineer with RAG/LLM experience",
    },
    budget_min: 6000,
    budget_max: 15000,
    budget_currency: "USD",
    timeline_weeks: 6,
    category: "AI Agents",
    scope: "medium",
    complexity: "medium",
    required_skills: ["Python", "LangChain", "Vector DB", "React", "OpenAI"],
    preferred_tech_stack: ["LangChain", "Qdrant", "GPT-4o", "Next.js", "Tailwind"],
    success_criteria: "Index 10k+ docs, <2s query time, 95%+ relevance, Slack integration for inline queries",
    status: "open",
    visibility: "public",
    views_count: 58,
    interest_count: 7,
    created_at: "2026-07-14T12:00:00Z",
    updated_at: "2026-07-19T09:00:00Z",
    creator: {
      id: "f3",
      username: "elenar",
      full_name: "Elena Rodriguez",
      avatar_url: null,
      bio: "Head of Knowledge at DocuAI",
      stack: ["AI", "NLP", "Product"],
      social_links: {},
      github_username: "elenar",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 95,
      role: "founder",
      is_verified: true,
      created_at: "2026-02-01T00:00:00Z",
      updated_at: "2026-07-10T00:00:00Z",
    },
  },
  {
    id: "hp-4",
    creator_id: "f1",
    title: "Voice AI Agent for Cold Outreach",
    description: "Build a voice AI agent that makes automated cold calls for sales outreach. Must use Twilio, Whisper for STT, and a natural-sounding TTS. Should handle objections and book meetings.",
    ai_parsed_requirements: {
      core_requirement: "Voice AI agent for automated sales calls",
      integrations: ["Twilio", "HubSpot", "Calendly"],
      tech_stack: ["Python", "Twilio", "Whisper", "ElevenLabs", "FastAPI"],
      complexity: "high",
      ideal_builder_type: "Voice AI engineer with telephony experience",
    },
    budget_min: 15000,
    budget_max: 30000,
    budget_currency: "USD",
    timeline_weeks: 8,
    category: "AI Agents",
    scope: "large",
    complexity: "high",
    required_skills: ["Twilio", "Whisper", "TTS", "Python", "Sales Outreach"],
    preferred_tech_stack: ["Twilio", "Whisper", "ElevenLabs", "FastAPI", "PostgreSQL"],
    success_criteria: "Natural conversation flow, 30%+ meeting booking rate, handle 5+ objection types, HubSpot integration",
    status: "open",
    visibility: "public",
    views_count: 39,
    interest_count: 4,
    created_at: "2026-07-12T15:00:00Z",
    updated_at: "2026-07-18T11:00:00Z",
    creator: {
      id: "f1",
      username: "sarahchen",
      full_name: "Sarah Chen",
      avatar_url: null,
      bio: "Founder & CEO at SupportAI",
      stack: ["Product", "Design", "AI"],
      social_links: {},
      github_username: "sarahchen",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 88,
      role: "founder",
      is_verified: true,
      created_at: "2026-01-01T00:00:00Z",
      updated_at: "2026-07-01T00:00:00Z",
    },
  },
  {
    id: "hp-5",
    creator_id: "f2",
    title: "Cloud Cost Optimization Dashboard",
    description: "Build a dashboard that tracks AWS/GCP cloud spend across multiple accounts, identifies savings opportunities, and automates resource right-sizing recommendations.",
    ai_parsed_requirements: {
      core_requirement: "Multi-cloud cost optimization dashboard",
      integrations: ["AWS Cost Explorer", "GCP Billing", "Slack", "PagerDuty"],
      tech_stack: ["Python", "React", "PostgreSQL", "Docker", "Terraform"],
      complexity: "medium",
      ideal_builder_type: "DevOps/Cloud engineer with FinOps experience",
    },
    budget_min: 8000,
    budget_max: 18000,
    budget_currency: "USD",
    timeline_weeks: 6,
    category: "DevOps & Infrastructure",
    scope: "medium",
    complexity: "medium",
    required_skills: ["AWS", "GCP", "Python", "React", "Cost Optimization"],
    preferred_tech_stack: ["React", "Python", "AWS SDK", "GCP SDK", "Docker"],
    success_criteria: "Track 10+ accounts, identify $5k+ monthly savings, automated recommendations, Slack alerts for anomalies",
    status: "open",
    visibility: "public",
    views_count: 25,
    interest_count: 2,
    created_at: "2026-07-10T09:00:00Z",
    updated_at: "2026-07-17T13:00:00Z",
    creator: {
      id: "f2",
      username: "marcusj",
      full_name: "Marcus Johnson",
      avatar_url: null,
      bio: "CTO at DataFlow Inc",
      stack: ["Data Engineering", "Infrastructure", "Python"],
      social_links: {},
      github_username: "marcusj",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 92,
      role: "founder",
      is_verified: true,
      created_at: "2026-01-15T00:00:00Z",
      updated_at: "2026-07-05T00:00:00Z",
    },
  },
  {
    id: "hp-6",
    creator_id: "f3",
    title: "Automated Meeting Summarizer Bot",
    description: "Build a bot that joins Zoom/Google Meet calls, transcribes them, generates summaries with action items using AI, and posts to Slack/Notion.",
    ai_parsed_requirements: {
      core_requirement: "Automated meeting transcription and summarization bot",
      integrations: ["Zoom API", "Google Meet", "Slack", "Notion"],
      tech_stack: ["Python", "OpenAI Whisper", "GPT-4o", "FastAPI"],
      complexity: "low",
      ideal_builder_type: "Full-stack developer with API integration experience",
    },
    budget_min: 4000,
    budget_max: 8000,
    budget_currency: "USD",
    timeline_weeks: 3,
    category: "Automation",
    scope: "small",
    complexity: "low",
    required_skills: ["Python", "API Integration", "OpenAI", "Transcription"],
    preferred_tech_stack: ["Python", "Whisper", "GPT-4o", "FastAPI", "Notion API"],
    success_criteria: "Join meetings automatically, <2min post-meeting summary, action items extracted, Slack + Notion posting",
    status: "open",
    visibility: "public",
    views_count: 71,
    interest_count: 9,
    created_at: "2026-07-08T11:00:00Z",
    updated_at: "2026-07-16T08:00:00Z",
    creator: {
      id: "f3",
      username: "elenar",
      full_name: "Elena Rodriguez",
      avatar_url: null,
      bio: "Head of Knowledge at DocuAI",
      stack: ["AI", "NLP", "Product"],
      social_links: {},
      github_username: "elenar",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 95,
      role: "founder",
      is_verified: true,
      created_at: "2026-02-01T00:00:00Z",
      updated_at: "2026-07-10T00:00:00Z",
    },
  },
  {
    id: "hp-7",
    creator_id: "f1",
    title: "Internal Developer Portal (IDP)",
    description: "Build an internal developer portal with Backstage-like functionality: service catalog, software templates, tech docs, and CI/CD integrations.",
    ai_parsed_requirements: {
      core_requirement: "Internal developer portal with service catalog and templates",
      integrations: ["GitHub", "GitLab", "Jenkins", "Docker"],
      tech_stack: ["React", "Node.js", "PostgreSQL", "Docker", "Kubernetes"],
      complexity: "high",
      ideal_builder_type: "Platform engineer with Backstage/IDP experience",
    },
    budget_min: 20000,
    budget_max: 40000,
    budget_currency: "USD",
    timeline_weeks: 12,
    category: "DevOps & Infrastructure",
    scope: "large",
    complexity: "high",
    required_skills: ["React", "Node.js", "Kubernetes", "CI/CD", "Developer Tools"],
    preferred_tech_stack: ["React", "Node.js", "PostgreSQL", "Kubernetes", "Argo CD"],
    success_criteria: "50+ services cataloged, 10+ software templates, self-service CI/CD, tech docs with search",
    status: "open",
    visibility: "public",
    views_count: 19,
    interest_count: 6,
    created_at: "2026-07-05T14:00:00Z",
    updated_at: "2026-07-15T10:00:00Z",
    creator: {
      id: "f1",
      username: "sarahchen",
      full_name: "Sarah Chen",
      avatar_url: null,
      bio: "Founder & CEO at SupportAI",
      stack: ["Product", "Design", "AI"],
      social_links: {},
      github_username: "sarahchen",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 88,
      role: "founder",
      is_verified: true,
      created_at: "2026-01-01T00:00:00Z",
      updated_at: "2026-07-01T00:00:00Z",
    },
  },
  {
    id: "hp-8",
    creator_id: "f3",
    title: "AI Code Review Assistant",
    description: "Build a GitHub App that automatically reviews PRs using AI, provides inline code suggestions, detects bugs, and enforces coding standards.",
    ai_parsed_requirements: {
      core_requirement: "AI-powered GitHub PR review assistant",
      integrations: ["GitHub API", "Slack"],
      tech_stack: ["Python", "GPT-4o", "FastAPI", "Docker"],
      complexity: "medium",
      ideal_builder_type: "Developer tooling engineer with AI experience",
    },
    budget_min: 7000,
    budget_max: 14000,
    budget_currency: "USD",
    timeline_weeks: 5,
    category: "Developer Tools",
    scope: "medium",
    complexity: "medium",
    required_skills: ["Python", "GitHub API", "AI/LLM", "Code Review", "Docker"],
    preferred_tech_stack: ["Python", "GPT-4o", "FastAPI", "Docker", "GitHub App"],
    success_criteria: "Review PRs in <30s, catch 80%+ of bugs, enforce team coding standards, Slack notifications",
    status: "open",
    visibility: "public",
    views_count: 44,
    interest_count: 8,
    created_at: "2026-07-03T16:00:00Z",
    updated_at: "2026-07-14T12:00:00Z",
    creator: {
      id: "f3",
      username: "elenar",
      full_name: "Elena Rodriguez",
      avatar_url: null,
      bio: "Head of Knowledge at DocuAI",
      stack: ["AI", "NLP", "Product"],
      social_links: {},
      github_username: "elenar",
      github_id: null,
      github_access_token: null,
      ships_count: 0,
      stars_count: 0,
      vibe_score: 95,
      role: "founder",
      is_verified: true,
      created_at: "2026-02-01T00:00:00Z",
      updated_at: "2026-07-10T00:00:00Z",
    },
  },
];

export const MOCK_MATCHES: Record<string, BuilderMatch[]> = {
  "hp-1": [
    {
      id: "m-1",
      project_id: "hp-1",
      builder_id: "b1",
      builder: {
        id: "b1",
        username: "alexrivera",
        full_name: "Alex Rivera",
        avatar_url: null,
        bio: "AI engineer specializing in chatbots and conversational AI. 5+ years experience.",
        stack: ["Claude", "Python", "FastAPI", "LangChain", "SLack API"],
        social_links: {},
        github_username: "alexrivera",
        github_id: null,
        github_access_token: null,
        ships_count: 8,
        stars_count: 24,
        vibe_score: 94,
        role: "builder",
        is_verified: true,
        created_at: "2025-06-01T00:00:00Z",
        updated_at: "2026-07-01T00:00:00Z",
      },
      match_score: 94,
      match_reasons: [
        "Built 3 similar AI chatbot projects",
        "1200+ hours Claude expertise",
        "Strong Slack API integration experience",
        "Available immediately",
      ],
      skills_match: ["Claude", "Python", "API Integration", "AI Agents"],
      experience_match: "Built AI support chatbots for 3 companies including a 100k+ user deployment",
      invited: false,
      invitation_sent_at: null,
      invitation_response: null,
    },
    {
      id: "m-2",
      project_id: "hp-1",
      builder_id: "b2",
      builder: {
        id: "b2",
        username: "priyasharma",
        full_name: "Priya Sharma",
        avatar_url: null,
        bio: "Full-stack AI engineer. Expert in LLM integration and API development.",
        stack: ["Python", "FastAPI", "PostgreSQL", "React", "Docker"],
        social_links: {},
        github_username: "priyasharma",
        github_id: null,
        github_access_token: null,
        ships_count: 6,
        stars_count: 18,
        vibe_score: 89,
        role: "builder",
        is_verified: false,
        created_at: "2025-08-15T00:00:00Z",
        updated_at: "2026-06-20T00:00:00Z",
      },
      match_score: 87,
      match_reasons: [
        "Built 2 similar chatbot projects",
        "Strong API integration portfolio",
        "Available in 2 weeks",
      ],
      skills_match: ["Python", "API Integration", "PostgreSQL"],
      experience_match: "Developed customer support chatbots for e-commerce and SaaS platforms",
      invited: false,
      invitation_sent_at: null,
      invitation_response: null,
    },
    {
      id: "m-3",
      project_id: "hp-1",
      builder_id: "b3",
      builder: {
        id: "b3",
        username: "jordanlee",
        full_name: "Jordan Lee",
        avatar_url: null,
        bio: "AI/ML engineer focused on NLP and conversational AI systems.",
        stack: ["Python", "PyTorch", "LangChain", "AWS", "Docker"],
        social_links: {},
        github_username: "jordanlee",
        github_id: null,
        github_access_token: null,
        ships_count: 11,
        stars_count: 35,
        vibe_score: 97,
        role: "builder",
        is_verified: true,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-07-05T00:00:00Z",
      },
      match_score: 82,
      match_reasons: [
        "Deep NLP/AI expertise",
        "Built a multi-tenant chatbot platform",
        "Available in 1 week",
      ],
      skills_match: ["Python", "AI Agents", "API Integration"],
      experience_match: "Built a multi-tenant conversational AI platform serving 50+ businesses",
      invited: false,
      invitation_sent_at: null,
      invitation_response: null,
    },
  ],
  "hp-3": [
    {
      id: "m-4",
      project_id: "hp-3",
      builder_id: "b3",
      builder: {
        id: "b3",
        username: "jordanlee",
        full_name: "Jordan Lee",
        avatar_url: null,
        bio: "AI/ML engineer focused on NLP and conversational AI systems.",
        stack: ["Python", "PyTorch", "LangChain", "AWS", "Docker"],
        social_links: {},
        github_username: "jordanlee",
        github_id: null,
        github_access_token: null,
        ships_count: 11,
        stars_count: 35,
        vibe_score: 97,
        role: "builder",
        is_verified: true,
        created_at: "2025-03-01T00:00:00Z",
        updated_at: "2026-07-05T00:00:00Z",
      },
      match_score: 96,
      match_reasons: [
        "Built 4 RAG systems in production",
        "Expert in LangChain + Qdrant",
        "Previously built similar documentation Q&A",
      ],
      skills_match: ["Python", "LangChain", "Vector DB", "OpenAI"],
      experience_match: "Architected RAG systems for 4 enterprises including legal document retrieval",
      invited: false,
      invitation_sent_at: null,
      invitation_response: null,
    },
    {
      id: "m-5",
      project_id: "hp-3",
      builder_id: "b1",
      builder: {
        id: "b1",
        username: "alexrivera",
        full_name: "Alex Rivera",
        avatar_url: null,
        bio: "AI engineer specializing in chatbots and conversational AI. 5+ years experience.",
        stack: ["Claude", "Python", "FastAPI", "LangChain", "SLack API"],
        social_links: {},
        github_username: "alexrivera",
        github_id: null,
        github_access_token: null,
        ships_count: 8,
        stars_count: 24,
        vibe_score: 94,
        role: "builder",
        is_verified: true,
        created_at: "2025-06-01T00:00:00Z",
        updated_at: "2026-07-01T00:00:00Z",
      },
      match_score: 79,
      match_reasons: [
        "LangChain experience",
        "React frontend capability",
        "Available immediately",
      ],
      skills_match: ["Python", "LangChain", "React"],
      experience_match: "Built AI applications with LangChain including RAG pipelines",
      invited: false,
      invitation_sent_at: null,
      invitation_response: null,
    },
  ],
};

export const MOCK_INVITATIONS: Invitation[] = [
  {
    id: "inv-1",
    project_id: "hp-1",
    project: MOCK_HIRE_PROJECTS[0],
    creator_id: "f1",
    creator: MOCK_HIRE_PROJECTS[0].creator,
    builder_id: "b1",
    personalized_message: "Alex, your work on AI chatbots caught my eye. You've built 3 similar projects — your expertise in Claude + Slack is exactly what this needs. Would love to discuss.",
    status: "pending",
    sent_at: "2026-07-21T14:00:00Z",
    responded_at: null,
  },
  {
    id: "inv-2",
    project_id: "hp-3",
    project: MOCK_HIRE_PROJECTS[2],
    creator_id: "f3",
    creator: MOCK_HIRE_PROJECTS[2].creator,
    builder_id: "b3",
    personalized_message: "Jordan, your RAG experience is impressive. Building 4 production RAG systems is exactly the track record we need for our documentation Q&A system. Let's chat!",
    status: "accepted",
    sent_at: "2026-07-18T10:00:00Z",
    responded_at: "2026-07-19T08:00:00Z",
  },
];

export const CATEGORIES = [
  "AI Agents",
  "Data Engineering",
  "DevOps & Infrastructure",
  "Developer Tools",
  "Automation",
  "Web Development",
  "Mobile Development",
  "Blockchain",
  "Design & UI",
  "Other",
] as const;

export const BUDGET_RANGES = [
  { label: "Any", min: 0, max: Infinity },
  { label: "Under $5k", min: 0, max: 5000 },
  { label: "$5k – $10k", min: 5000, max: 10000 },
  { label: "$10k – $20k", min: 10000, max: 20000 },
  { label: "$20k – $50k", min: 20000, max: 50000 },
  { label: "$50k+", min: 50000, max: Infinity },
] as const;

export const TIMELINE_OPTIONS = [
  { label: "Any", weeks: 0 },
  { label: "1–2 weeks", weeks: 2 },
  { label: "3–4 weeks", weeks: 4 },
  { label: "5–8 weeks", weeks: 8 },
  { label: "9+ weeks", weeks: 12 },
] as const;
